apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment-deploy
  labels:
    app: assignment-app
spec:
  selector:
    matchLabels:
      app: assignment-app
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: assignment-app
    spec:
      containers:
        - name: assignment-app
          image: aryanjadon94/python:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "64Mi"
              cpu : "50m"
            limits:
              memory: "256Mi"
              cpu: "500m"
